name: Create env file

on:
  push:
    branches: [ "create_env_file" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # -----------------------
    # Create .env
    # -----------------------
    - name: Create env file
    - run: |
        touch .env
        echo ENV_VALUE=${{ secrets.SAMPLE_ENV_VALUE }} >> .env
        cat .env