name: create_artifacts

on:
  push:
    branches: [ "send_file" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: mkdir -p path/to/artifacts
    - run: echo hello > path/to/artifacts/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifacts/world.txt
        
    - uses: actions/download-artifact@v3
      id: test
      with:
        name: 'my-artifact'
        path: path/to/artifacts