name: create_artifacts

on:
  push:
    branches: [ "send_file" ]

jobs:
  create_artifacts:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create artifacts
      run: |
        mkdir -p path/to/artifacts
        echo hello > path/to/artifacts/world.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifacts
        path: path/to/artifacts/world.txt
        
    # - name: Download artifacts
    #   uses: actions/download-artifact@v3
    #   id: test
    #   with:
    #     name: my-artifacts
    #     path: path/to/artifacts